### ISSUE TITLE
react-color

### ISSUE THREAD

**Issue by N4N1T0** [N4N1T0/Tshirt-ThreeJS#10]
<html>
<body>

src/components/ColorPicker.tsx(1,30): error TS7016: Could not find a declaration file for module 'react-color'. '/vercel/path0/client/node_modules/.pnpm/react-color@2.19.3_react@18.2.0/node_modules/react-color/lib/index.js' implicitly has an 'any' type.
--
00:28:35.584 | Try `npm i --save-dev @types/react-color` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-color';`
00:28:35.602 | ELIFECYCLE  Command failed with exit code 2.
00:28:35.624 | Error: Command "pnpm run build" exited with 1

</body>
</html>

**Comment by DonMiller9294** [comment]
to resolve the error try 
rm -rf node_modules
npm install

in your terminal

**Comment by N4N1T0** [comment]
> to resolve the error try rm -rf node_modules npm install
> 
> in your terminal

Thanks Man, appreciate!

**Comment by DonMiller9294** [comment]
no problem.
